repos:
  - repo: local
    hooks:
      - id: check-commit-message
        name: Check Commit Message Format
        entry: ./check-commit-msg.sh
        language: script
        stages: [commit-msg]
